USE ELR_STYLE_PROJECT;

CREATE TABLE SUPPLIER (
SUPPLIER_ID INT NOT NULL,
SUPPLIER_NAME VARCHAR (30) NOT NULL,
SUPP_LOCATION VARCHAR (30) NOT NULL,
CATEGORY_ID INT NOT NULL,
CONSTRAINT PK_SUPPLIER_ID PRIMARY KEY(SUPPLIER_ID)
);

INSERT INTO SUPPLIER
(SUPPLIER_ID, SUPPLIER_NAME, SUPP_LOCATION, CATEGORY_ID)
VALUES
(4100, 'MNHFASHIONS', 'LONDON', 701),
(4200, 'AURORA', 'MANCHESTER', 702),
(4300, 'SUBLIME', 'MANCHESTER', 702),
(4400, 'ELRFACTORY', 'DUBAI', 701),
(4500, 'PHOENIXFASHIONS', 'LONDON', 703);

CREATE TABLE SUPPLIER_CATEGORY (
SUPP_CATEGORY_ID INT NOT NULL,
SUPP_CAT_NAME VARCHAR (25) NOT NULL,
CONSTRAINT PK_SUPP_CATEGORY_ID PRIMARY KEY(SUPP_CATEGORY_ID)
);

INSERT INTO SUPPLIER_CATEGORY
(SUPP_CATEGORY_ID, SUPP_CAT_NAME)
VALUES
(701, 'CLOTHING'),
(702, 'BAGS'),
(703, 'ACCESSORIES');

