CREATE OR REPLACE VIEW VW_PROMO_CODE AS

/* WHICH CUSTOMERS USED PROMO CODE AND WHICH DID NOT? */
SELECT DISTINCT Orders.Order_ID, Customer.First_Name, Customer.Customer_ID, Orders.ORDER_PROMO
FROM Orders
INNER JOIN Customer ON Orders.ORDER_Customer_ID = Customer.Customer_ID
ORDER BY ORDERS.ORDER_PROMO; 

CREATE OR REPLACE VIEW VW_ORDER_AMOUNT_PROMO AS
-- RIGHT JOIN MULTIPLE
/* WHAT IS THE CUSTOMER NAME AND ORDER AMOUNT FOR CUSTOMERS WHO HAVE USED THE PROMO CODE, WHICH PROMO CODE?*/

SELECT DISTINCT ORDERS.ORDER_AMOUNT, ORDERS.ORDER_ID, CUSTOMER.FIRST_NAME, ORDER_DETAILS.PROMOTION_ID
FROM ((ORDERS
RIGHT JOIN CUSTOMER ON ORDERS.ORDER_CUSTOMER_ID = CUSTOMER.CUSTOMER_ID)
RIGHT JOIN ORDER_DETAILS ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID)
WHERE order_details.promotion_id IS NOT NULL
ORDER BY ORDERS.ORDER_ID;

