
SELECT * FROM PRODUCT;
-- Add a product to the products table
DELIMITER //
CREATE PROCEDURE AddProduct(
IN PRODUCT_ID INT,
IN PRODUCT_SKU VARCHAR(30),
IN PRODUCT_ITEM VARCHAR (100),
IN PRODUCT_PRICE FLOAT,
IN PRODUCT_CAT_ID INT,
IN PRODUCT_SUPP_ID INT,
IN PR_CREATED TIMESTAMP,
IN PR_MODIFIED TIMESTAMP)
BEGIN

INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_SKU, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CAT_ID, PRODUCT_SUPP_ID, PR_CREATED, PR_MODIFIED)
VALUES (PRODUCT_ID, PRODUCT_SKU, PRODUCT_ITEM, PRODUCT_PRICE, PRODUCT_CAT_ID, PRODUCT_SUPP_ID, PR_CREATED, PR_MODIFIED);

END//
-- Change Delimiter again
DELIMITER ;

CALL AddProduct (1120, 'MIN_BAG', 'ELR MINI HANDBAG', 30, 552, 4500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


SELECT *
FROM PRODUCT;

DROP PROCEDURE AddProduct;
