-- FUNCTION: Categorise stock levels for each item
DELIMITER //
CREATE FUNCTION RESTOCK_ALERT(
    QUANTITY INT
) 
RETURNS VARCHAR(20)
DETERMINISTIC
BEGIN
    DECLARE RESTOCK_ALERT VARCHAR(20);
    IF QUANTITY <= 20 THEN
        SET RESTOCK_ALERT = 'URGENT RESTOCK';
    ELSEIF QUANTITY >= 100 THEN
        SET RESTOCK_ALERT = 'IN STOCK';
    ELSEIF QUANTITY <= 50 THEN
        SET RESTOCK_ALERT = 'LOW STOCK';
    END IF;
    RETURN (RESTOCK_ALERT);
END//QUANTITY
DELIMITER ;

select * from ELR_PROJECT.PRODUCT_INVENTORY;

SELECT
	INVENTORY_ID,
	PRODUCT_ID,
	COLOUR,
	QUANTITY,
	INV_SUPPLIER_ID,
	RESTOCK_ALERT(QUANTITY)
FROM 
	PRODUCT_INVENTORY;
